#!/usr/bin/with-contenv sh


echo "================================="
echo $HL_USER_USERNAME
echo "================================="

source /etc/hluser

homedir=$( getent passwd "$HL_USER_USERNAME" | cut -d: -f6 )
userid=$( id -u "$HL_USER_USERNAME" ) 
groupid=$( id -g "$HL_USER_USERNAME" )
cd $homedir
echo "running ttyd with the uid: " $userid
echo "running ttyd with the gid: " $groupid
echo "running ttyd in the following homedir: " $homedir
echo "permissions in $homedir"
ls -al $homedir
ls -lt /

chown -R $userid /home/HL_USER_USERNAME
chmod 640 /home/HL_USER_USERNAME/.bashrc
sed -i -e "s/HL_USER_USERNAME/$HL_USER_USERNAME/g" /home/HL_USER_USERNAME/.bashrc
sed -i -e "s/HL_USER_USERNAME/$HL_USER_USERNAME/g" /etc/bashrc
chown -R root:root /home/HL_USER_USERNAME/bin

cp -rf /home/HL_USER_USERNAME/* /home/$HL_USER_USERNAME/
cp /home/HL_USER_USERNAME/.bashrc /home/$HL_USER_USERNAME/.bashrc
chown -R $HL_USER_USERNAME:$HL_USER_USERNAME /home/$HL_USER_USERNAME
chown -R root:root /home/$HL_USER_USERNAME/bin


exec /usr/bin/ttyd -u $userid -g $groupid bash --rcfile /etc/bashrc;
#exec ttyd -B -u $userid -g $groupid bash --rcfile /etc/bashrc;
